"""empty message

Revision ID: 48c6af40bba1
Revises: ec8556e34b31
Create Date: 2022-10-15 09:33:40.335824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c6af40bba1'
down_revision = 'ec8556e34b31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('usuario', sa.String(), nullable=False))
    op.drop_column('user', 'name')
    op.drop_column('user', 'cpf')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cpf', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user', 'usuario')
    # ### end Alembic commands ###
