"""empty message

Revision ID: b2823eb3f623
Revises: 48c6af40bba1
Create Date: 2022-10-15 09:39:49.193040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2823eb3f623'
down_revision = '48c6af40bba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user', sa.String(), nullable=False))
    op.drop_column('user', 'usuario')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('usuario', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user', 'user')
    # ### end Alembic commands ###
