"""empty message

Revision ID: e4ce0f1ebfa8
Revises: 555e650c8cac
Create Date: 2022-09-05 10:58:22.373433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4ce0f1ebfa8'
down_revision = '555e650c8cac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('trash', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'trash')
    # ### end Alembic commands ###
