"""empty message

Revision ID: fd08ac283ac4
Revises: e4ce0f1ebfa8
Create Date: 2022-09-05 11:45:31.773050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd08ac283ac4'
down_revision = 'e4ce0f1ebfa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('removal', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'removal')
    # ### end Alembic commands ###
